### ISSUE TITLE
KIAM service account key name incorrect

### ISSUE THREAD

**Issue by jhosteny** [cloudposse/helmfiles#209]
As seen in version 2.5.2 of the chart [here](https://github.com/helm/charts/blob/3a64be0aec0bc0cbf7bfff18c9b78f07c4b4d69d/stable/kiam/values.yaml#L274), and in the new chart location [here](https://github.com/uswitch/kiam/blob/fad5afc6c54ce68348f4eb2310cf39fa603b38ce/helm/kiam/values.yaml#L321), the key name should be `serviceAccounts`, not `serviceAccount`.

A PR will follow shortly.

**Comment by 3h4x** [comment]
Closing as changes are merged already
