### ISSUE TITLE
Codefresh question

### ISSUE THREAD

**Issue by jbadeau** [cloudposse/helmfiles#232]
Hi,

I have a few question about codefresh:

1. Are the codefresh helmcharts for installing  the onprem version of codefresh?
2. Are you still using codefresh as your CI/CD tool?
3. If yes, do you have any tips, best practices or even actual pipelines and/or steps you can share?

**Comment by osterman** [comment]
> Are the codefresh helmcharts for installing the onprem version of codefresh?

Yes, we have one for that, but no longer support it. We're no longer supporting any customers using codefresh on-prem

> Are you still using codefresh as your CI/CD tool?

Yes, very much so. Just not the on-prem edition.

> If yes, do you have any tips, best practices or even actual pipelines and/or steps you can share?

Please book a call at https://cloudposse.com/quiz and I'll be happy to guide you through it and show you actual examples.
