### ISSUE TITLE
[nginx-ingress] Upgrade to 0.15.0

### ISSUE THREAD

**Issue by osterman** [cloudposse/helmfiles#31]
## what
* Upgrade `nginx-ingress` to use docker image 0.15.0

## why
* Fix race condition when using TLS and kube-lego

## references
* https://sweetops.slack.com/archives/CBW699XE0/p1535138518000100

**Comment by alebabai** [comment]
@osterman  
`nginx-ingress` chart has been upgraded to 0.26.0 and it uses 0.18.0 image version.
May be it's better to upgrade the whole chart?

**Comment by osterman** [comment]
@goruha where is the work you're doing on using the official nginx ingress? Maybe it overlaps with this task.
