### ISSUE TITLE
Identify Charts that Need RBAC Enabled

### ISSUE THREAD

**Issue by osterman** [cloudposse/helmfiles#34]
## what
* Identify all charts that need RBAC enabled
* Create issue in this repo and associate with `PCI/Security` project

## why
* PCI/Security compliance

**Comment by alebabai** [comment]
@osterman may be it would be better to create a single PR with RBAC enabled by default in all charts that support it instead of creating issue for each helmfile.

**Comment by alebabai** [comment]
@osterman 
Or even better solution:
I can parametrize rbac based on global env `KOPS_AUTHORIZATION_RBAC_ENABLED`.
Something like that:
```go
{{  env "KOPS_AUTHORIZATION_RBAC_ENABLED" | default "false" }}
```

**Comment by osterman** [comment]
That's interesting - I'm not sure the best approach.

Keep in mind we would like most of these to work on EKS, GKE in addition to Kops.

My main concern is to reduce the size of the PR. So if we can do everything in one smallish PR, I'm okay with it.
